SQL_QUERY_FEATURE_ROLLING = """
WITH "CTE_OFFER_STATS" AS (
   SELECT
      "ANIOCAMPANA", "CODPAIS", "OFFERID", "DESCRIPCIONROLLING", count(*) as "CNT"
   FROM
      "table_dd"
   GROUP BY
      "ANIOCAMPANA", "CODPAIS", "OFFERID", "DESCRIPCIONROLLING"
),  
"CTE_OFFER_STATS_CNT" AS (
    SELECT
        "ANIOCAMPANA",
        "CODPAIS",
        "OFFERID",
        "DESCRIPCIONROLLING",
        "CNT",e
        "CNT" * 1.0 / SUM("CNT") OVER (PARTITION BY "OFFERID") AS "RATIO"
    FROM "CTE_OFFER_STATS"
)
SELECT 
    "ANIOCAMPANA",
    "CODPAIS",
    "OFFERID",
    SUM(CASE WHEN "DESCRIPCIONROLLING" = 'Constantes 1' THEN "CNT" ELSE 0 END) AS "CNT_CONSTANTES_1",
    SUM(CASE WHEN "DESCRIPCIONROLLING" = 'Constantes 2' THEN "CNT" ELSE 0 END) AS "CNT_CONSTANTES_2",
    SUM(CASE WHEN "DESCRIPCIONROLLING" = 'Constantes 3' THEN "CNT" ELSE 0 END) AS "CNT_CONSTANTES_3",
    SUM(CASE WHEN "DESCRIPCIONROLLING" = 'Inconstantes' THEN "CNT" ELSE 0 END) AS "CNT_INCONSTANTES",
    SUM(CASE WHEN "DESCRIPCIONROLLING" = 'Sin Segmento' THEN "CNT" ELSE 0 END) AS "CNT_SIN_SEGMENTO",
    SUM(CASE WHEN "DESCRIPCIONROLLING" = 'Tops' THEN "CNT" ELSE 0 END) AS "CNT_TOPS",
    SUM(CASE WHEN "DESCRIPCIONROLLING" = 'Nuevas' THEN "CNT" ELSE 0 END) AS "CNT_NUEVAS",
    SUM(CASE WHEN "DESCRIPCIONROLLING" = 'Brilla' THEN "CNT" ELSE 0 END) AS "CNT_BRILLA",
    SUM(CASE WHEN "DESCRIPCIONROLLING" = '' THEN "CNT" ELSE 0 END) AS "CNT_EMPTYSTRING",
    SUM(CASE WHEN "DESCRIPCIONROLLING" = 'Constantes 1' THEN "RATIO" ELSE 0 END) AS "RATIO_CONSTANTES_1",
    SUM(CASE WHEN "DESCRIPCIONROLLING" = 'Constantes 2' THEN "RATIO" ELSE 0 END) AS "RATIO_CONSTANTES_2",
    SUM(CASE WHEN "DESCRIPCIONROLLING" = 'Constantes 3' THEN "RATIO" ELSE 0 END) AS "RATIO_CONSTANTES_3",
    SUM(CASE WHEN "DESCRIPCIONROLLING" = 'Inconstantes' THEN "RATIO" ELSE 0 END) AS "RATIO_INCONSTANTES",
    SUM(CASE WHEN "DESCRIPCIONROLLING" = 'Sin Segmento' THEN "RATIO" ELSE 0 END) AS "RATIO_SIN_SEGMENTO",
    SUM(CASE WHEN "DESCRIPCIONROLLING" = 'Tops' THEN "RATIO" ELSE 0 END) AS "RATIO_TOPS",
    SUM(CASE WHEN "DESCRIPCIONROLLING" = 'Nuevas' THEN "RATIO" ELSE 0 END) AS "RATIO_NUEVAS",
    SUM(CASE WHEN "DESCRIPCIONROLLING" = 'Brilla' THEN "RATIO" ELSE 0 END) AS "RATIO_BRILLA",
    SUM(CASE WHEN "DESCRIPCIONROLLING" = '' THEN "RATIO" ELSE 0 END) AS "RATIO_EMPTYSTRING"    
FROM "CTE_OFFER_STATS_CNT"
GROUP BY
  "ANIOCAMPANA", "CODPAIS", "OFFERID"
;
"""

SQL_QUERY_FEATURE_ORDEN = """
SELECT 
    "ANIOCAMPANA",
    "CODPAIS",
    "OFFERID",
    "QUARTILE",
    MIN("ORDEN") AS "MIN_ORDEN",
    MAX("ORDEN") AS "MAX_ORDEN",
    AVG("ORDEN") AS "AVG_ORDEN",
    STDDEV("ORDEN") AS "STD_ORDEN",
    COUNT("ORDEN") AS "CTD_ORDEN"
FROM "table_dd" AS "T1"
GROUP BY "ANIOCAMPANA", "CODPAIS", "OFFERID", "QUARTILE";
"""

SQL_QUERY_FEATURE_QUARTILE = """
SELECT
    "ANIOCAMPANA",
    "CODPAIS",
    "OFFERID",
    MAX(CASE WHEN "QUARTILE" = 1 THEN "MIN_ORDEN" END) AS "MIN_ORDEN_Q1",
    MAX(CASE WHEN "QUARTILE" = 2 THEN "MIN_ORDEN" END) AS "MIN_ORDEN_Q2",
    MAX(CASE WHEN "QUARTILE" = 3 THEN "MIN_ORDEN" END) AS "MIN_ORDEN_Q3",
    MAX(CASE WHEN "QUARTILE" = 4 THEN "MIN_ORDEN" END) AS "MIN_ORDEN_Q4",
    MAX(CASE WHEN "QUARTILE" = 1 THEN "MAX_ORDEN" END) AS "MAX_ORDEN_Q1",
    MAX(CASE WHEN "QUARTILE" = 2 THEN "MAX_ORDEN" END) AS "MAX_ORDEN_Q2",
    MAX(CASE WHEN "QUARTILE" = 3 THEN "MAX_ORDEN" END) AS "MAX_ORDEN_Q3",
    MAX(CASE WHEN "QUARTILE" = 4 THEN "MAX_ORDEN" END) AS "MAX_ORDEN_Q4",
    MAX(CASE WHEN "QUARTILE" = 1 THEN "AVG_ORDEN" END) AS "AVG_ORDEN_Q1",
    MAX(CASE WHEN "QUARTILE" = 2 THEN "AVG_ORDEN" END) AS "AVG_ORDEN_Q2",
    MAX(CASE WHEN "QUARTILE" = 3 THEN "AVG_ORDEN" END) AS "AVG_ORDEN_Q3",
    MAX(CASE WHEN "QUARTILE" = 4 THEN "AVG_ORDEN" END) AS "AVG_ORDEN_Q4",
    MAX(CASE WHEN "QUARTILE" = 1 THEN "MEDIAN_ORDEN" END) AS "MEDIAN_ORDEN_Q1",
    MAX(CASE WHEN "QUARTILE" = 2 THEN "MEDIAN_ORDEN" END) AS "MEDIAN_ORDEN_Q2",
    MAX(CASE WHEN "QUARTILE" = 3 THEN "MEDIAN_ORDEN" END) AS "MEDIAN_ORDEN_Q3",
    MAX(CASE WHEN "QUARTILE" = 4 THEN "MEDIAN_ORDEN" END) AS "MEDIAN_ORDEN_Q4",
    MAX(CASE WHEN "QUARTILE" = 1 THEN "STD_ORDEN" END) AS "STD_ORDEN_Q1",
    MAX(CASE WHEN "QUARTILE" = 2 THEN "STD_ORDEN" END) AS "STD_ORDEN_Q2",
    MAX(CASE WHEN "QUARTILE" = 3 THEN "STD_ORDEN" END) AS "STD_ORDEN_Q3",
    MAX(CASE WHEN "QUARTILE" = 4 THEN "STD_ORDEN" END) AS "STD_ORDEN_Q4",
    MAX(CASE WHEN "QUARTILE" = 1 THEN "CTD_ORDEN" END) AS "CTD_ORDEN_Q1",
    MAX(CASE WHEN "QUARTILE" = 2 THEN "CTD_ORDEN" END) AS "CTD_ORDEN_Q2",
    MAX(CASE WHEN "QUARTILE" = 3 THEN "CTD_ORDEN" END) AS "CTD_ORDEN_Q3",
    MAX(CASE WHEN "QUARTILE" = 4 THEN "CTD_ORDEN" END) AS "CTD_ORDEN_Q4"
FROM "table_dd"
GROUP BY "ANIOCAMPANA","CODPAIS","OFFERID";
"""

SQL_QUERY_FEATURE_CONSULTORAS_EXPS = """
SELECT 
    "ANIOCAMPANA",
    "CODPAIS",
    "OFFERID",
    COUNT(DISTINCT "CODEBELISTA") CTD_CONSULTORAS_EXPUESTAS
FROM "table_dd" 
GROUP BY "ANIOCAMPANA", "CODPAIS", "OFFERID";
"""

SQL_QUERY_FEATURE_PRIORIDAD_EVENTO = """
SELECT 
    "CODPAIS",
    "ANIOCAMPANA",
    "OFFERID",
    MAX("PRIORIDADEVENTO") AS "PRIORIDADEVENTO"
FROM "table_dd"
GROUP BY "CODPAIS", "ANIOCAMPANA", "OFFERID";
"""

SQL_QUERY_FEATURE_FACTOR_REPETICION  = """
SELECT 
    "COD_PERIODO",
    "COD_PAIS",
    "ALCANCE",
    "COD_MEDIOVENTA",
    "COD_SUBESTRATEGIA",
    "ID_OFERTA",
    "ID_SUBESTRATEGIA",
    "COD_GRUPO",
    "ES_GRUPO_PADRE",
    "COD_SUBGRUPO",
    "COD_TIPO_GRUPO",
    "COD_TIPO_SUBGRUPO",
    "COD_CUC",
    "ES_PADRE",
    "PRECIO_OFERTA",
    "PRECIO_NORMAL",
    "FACTOR_CUADRE",
    CASE
        WHEN "FACTOR_REPETICION" IS NULL THEN 1
        ELSE CAST("FACTOR_REPETICION" AS INT)
    END AS "FACTOR_REPETICION",
    CASE
        WHEN "COD_MEDIOVENTA" IN ('09', '10', '13', '27', '40', '41', '42') THEN 'B'
        ELSE 'A'
    END AS "TARGET"
FROM "table_dd";
"""
